import re


# Words indicating high-quality benchmark datasets
GOOD_KEYWORDS = [
    "benchmark",
    "dataset",
    "real",
    "fake",
    "deepfake",
    "synthetic",
    "face",
    "image",
    "video",
    "audio",
    "voice",
    "multimodal",
    "forgery",
    "detection",
    "classification",
    "celeb",
    "ff++",
    "faceswap",
]

BAD_KEYWORDS = [
    "hw",
    "assignment",
    "practice",
    "tutorial",
    "test",
    "example",
    "demo",
]


def quality_score(item):

    score = 0

    title = item.get("title", "").lower()
    description = item.get("description", "").lower()

    text = title + " " + description

    # -------------------------
    # Good keywords
    # -------------------------
    for word in GOOD_KEYWORDS:

        if word in text:
            score += 5

    # -------------------------
    # Bad keywords
    # -------------------------
    for word in BAD_KEYWORDS: 

        if word in text:
            score -= 15

    # -------------------------
    # Description length
    # -------------------------
    length = len(description)

    if length > 100:
        score += 10
    
    if length > 500:
        score += 10

    # -------------------------
    # Recent datasets
    # -------------------------
    updated = item.get("updated", "")

    if updated.startswith("2026"):
        score += 8

    elif updated.startswith("2025"):
        score += 5

    elif updated.startswith("2024"):
        score += 3

    # -------------------------
    # Penalize autogenerated repositories
    # -------------------------
    auto_words = [
        "generated by ml intern",
        "dataset card",
        "distilabel",
    ]

    for w in auto_words:

        if w in description:
            score -= 10

    return max(score, 0)