MIN_SCORE = 25

def is_valid(item):

    if item["quality_score"] < MIN_SCORE:
        return False

    title = item.get("title", "").lower()

    banned = [
        "assignment",
        "hw",
        "tutorial",
        "example",
        "generated by ml intern",
        "project1",
        "course",
        "practice",
        "demo",
    ]

    for word in banned:
        if word in title:
            return False

    return True